install.packages("FactoMineR")
install.packages("factoextra")
install.packages("Factoshiny")
install.packages("shiny")
install.packages("ggplot2")
install.packages("FactoInvestigate")
install.packages("readxl")
library(FactoMineR)
library(ggplot2)
library(factoextra)
library(shiny)
library(FactoInvestigate)
library(Factoshiny)
library(readxl)
Resistivity <- read_excel("C:/Users/aboulassel/Desktop/HCPC Dataset/Resistivity.xlsx")
View (Resistivity)
res.PCA <- PCA(Resistivity, quali.sup = c(1), graph = FALSE)
plot.PCA(res.PCA, choix = 'var', title = "Graphe des variables de l'ACP", col.var = '#FF0C08')
plot.PCA(res.PCA, invisible = c('quali', 'ind.sup'), habillage = 1, title = "Graphe des individus de l'ACP", label = 'none')
summary(res.PCA)
res.PCA <- PCA(Resistivity, ncp = 2, quali.sup = c(1), graph = FALSE)
dimdesc(res.PCA)
res.PCA <- PCA(Resistivity, ncp = Inf, scale.unit = FALSE, quali.sup = c(1), graph = FALSE)
res.HCPC <- HCPC(res.PCA, nb.clust = 3, consol = FALSE, graph = FALSE)
plot.HCPC(res.HCPC, choice = 'tree', title = 'Arbre hiérarchique')
plot.HCPC(res.HCPC, choice = 'map', draw.tree = FALSE, title = 'Plan factoriel')
plot.HCPC(res.HCPC, choice = '3D.map', ind.names = FALSE, centers.plot = FALSE, angle = 89, title = 'Arbre hiérarchique sur le plan factoriel')
summary(res.HCPC)
